services:
  postgres:
    image: postgres:16

    volumes:
      [postgres-volume:/var/lib/postgresql/data]

    environment:
      POSTGRES_DB: l0_data
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

    networks:
      [postgres]

    ports:
      [5432:5432]

volumes:
  postgres-volume:

networks:
  postgres:
